const ENTITIES: Record<string, string> = {
  '&amp;':   '&',
  '&lt;':    '<',
  '&gt;':    '>',
  '&quot;':  '"',
  '&apos;':  "'",
  '&nbsp;':  ' ',
  '&aelig;': 'æ',
  '&AElig;': 'Æ',
  '&eacute;': 'é',
  '&Eacute;': 'É',
  '&egrave;': 'è',
  '&Egrave;': 'È',
  '&ecirc;':  'ê',
  '&Ecirc;':  'Ê',
  '&euml;':   'ë',
  '&iacute;': 'í',
  '&igrave;': 'ì',
  '&icirc;':  'î',
  '&iuml;':   'ï',
  '&oacute;': 'ó',
  '&Oacute;': 'Ó',
  '&ograve;': 'ò',
  '&ocirc;':  'ô',
  '&ouml;':   'ö',
  '&Ouml;':   'Ö',
  '&uacute;': 'ú',
  '&ugrave;': 'ù',
  '&ucirc;':  'û',
  '&uuml;':   'ü',
  '&ntilde;': 'ñ',
  '&Ntilde;': 'Ñ',
  '&ccedil;': 'ç',
  '&Ccedil;': 'Ç',
  '&szlig;':  'ß',
  '&agrave;': 'à',
  '&aacute;': 'á',
  '&acirc;':  'â',
  '&auml;':   'ä',
  '&#39;':    "'",
  '&#34;':    '"',
};

export function decodeHtml(str: string): string {
  return str.replace(/&[a-zA-Z]+;|&#\d+;/g, (entity) => ENTITIES[entity] ?? entity);
}
